[package]
name = "gpuequiv"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.18"
simple_logger = "4.2"
log = "0.4"
pollster = { version = "0.3", features = ["macro"] }
bytemuck = "1.14"
futures-intrusive = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[workspace]
members = [
    "run-wasm",
]
