[package]
name = "gpuequiv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.17"
simple_logger = "4.2.0"
log = "0.4.19"
pollster = "0.3.0"
bytemuck = "1.13.1"
futures-intrusive = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wasm-bindgen-futures = "0.4.37"
web-sys = "0.3.61"

[workspace]
members = [
    "run-wasm",
]
